# sd 基础模型
FROM alpine:3.17 as models

RUN apk add --no-cache aria2
RUN aria2c -x 8 --dir "/" --out "sd-v1-5-inpainting.ckpt" "https://huggingface.co/runwayml/stable-diffusion-inpainting/resolve/main/sd-v1-5-inpainting.ckpt"

FROM registry.cn-hangzhou.aliyuncs.com/aliyun-fc/fc-stable-diffusion:basev1

COPY --from=models /sd-v1-5-inpainting.ckpt /stable-diffusion-webui/models/Stable-diffusion/sd-v1-5-inpainting.ckpt

RUN sed -i /stable-diffusion-webui/ui-config.json -e 's@"txt2img/Prompt/value": ""@"txt2img/Prompt/value": "杰作，最佳质量，非常详细，极其精致美丽，超详细，蓬乱的头发，插图，动态角度，少女，时尚服装，站立，时装模特，看着观众，采访，沙滩，美丽详细的眼睛，精致美丽的脸，漂浮，高饱和度，美丽细致的光影"@'
RUN sed -i /stable-diffusion-webui/ui-config.json -e 's@"txt2img/Negative prompt/value": ""@"txt2img/Negative prompt/value": "loli,nsfw,logo,text,badhandv4,EasyNegative,ng_deepnegative_v1_75t,rev2-badprompt,verybadimagenegative_v1.3,negative_hand-neg,mutated hands and fingers,poorly drawn face,extra limb,missing limb,disconnected limbs,malformed hands,ugly"@'