# WebUI 基础镜像
# 包含 WebUI、相关依赖、插件、Lora、VAE

############################# 
#     clone repositories    #
#############################
FROM alpine/git:2.36.2 as repositories

COPY clone.sh /clone.sh

RUN . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6 \
    && rm -rf data assets **/*.ipynb

RUN . /clone.sh stable-diffusion-stability-ai https://github.com/Stability-AI/stablediffusion.git 47b6b607fdd31875c9279cd2f4f16b92e4ea958e \
    && rm -rf assets data/**/*.png data/**/*.jpg data/**/*.gif

RUN . /clone.sh CodeFormer https://github.com/sczhou/CodeFormer.git c5b4593074ba6214284d6acd5f1719b6c5d739af \
    && rm -rf assets inputs

RUN . /clone.sh BLIP https://github.com/salesforce/BLIP.git 48211a1594f1321b00f14c9f7a5b4813144b2fb9
RUN . /clone.sh k-diffusion https://github.com/crowsonkb/k-diffusion.git 5b3af030dd83e0297272d861c19477735d0317ec
RUN . /clone.sh clip-interrogator https://github.com/pharmapsychotic/clip-interrogator 2486589f24165c8e3b303f84e9dbbea318df83e8

############################# 
#     download xformers     #
#############################

FROM alpine:3.17 as xformers

RUN apk add --no-cache aria2
RUN aria2c -x 5 --dir / --out wheel.whl 'https://github.com/AbdBarho/stable-diffusion-webui-docker/releases/download/5.0.3/xformers-0.0.20.dev528-cp310-cp310-manylinux2014_x86_64-pytorch2.whl'

############################# 
#    base image with deps   #
#############################

FROM python:3.10.9-slim as base

ENV DEBIAN_FRONTEND=noninteractive PIP_PREFER_BINARY=1

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    # we need those
    apt-get install -y fonts-dejavu-core rsync git jq moreutils aria2 \
    # extensions needs those
    ffmpeg libglfw3-dev libgles2-mesa-dev pkg-config libcairo2 libcairo2-dev

RUN --mount=type=cache,target=/cache --mount=type=cache,target=/root/.cache/pip \
    aria2c -x 5 --dir /cache --out torch-2.0.0-cp310-cp310-linux_x86_64.whl -c \
    https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp310-cp310-linux_x86_64.whl && \
    pip install /cache/torch-2.0.0-cp310-cp310-linux_x86_64.whl torchvision --index-url https://download.pytorch.org/whl/cu118

RUN --mount=type=cache,target=/root/.cache/pip \
    git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git && \
    cd stable-diffusion-webui && \
    git reset --hard d7aec59c4eb02f723b3d55c6f927a42e97acd679 && \
    pip install -r requirements_versions.txt

RUN --mount=type=cache,target=/root/.cache/pip  \
    --mount=type=bind,from=xformers,source=/wheel.whl,target=/xformers-0.0.20.dev528-cp310-cp310-manylinux2014_x86_64.whl \
    pip install /xformers-0.0.20.dev528-cp310-cp310-manylinux2014_x86_64.whl

ENV ROOT=/stable-diffusion-webui


COPY --from=repositories /repositories/ ${ROOT}/repositories/
RUN mkdir ${ROOT}/interrogate && cp ${ROOT}/repositories/clip-interrogator/data/* ${ROOT}/interrogate
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r ${ROOT}/repositories/CodeFormer/requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install pyngrok \
    git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 \
    git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 \
    git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b

# Note: don't update the sha of previous versions because the install will take forever
# instead, update the repo state in a later step

# TODO: either remove if fixed in A1111 (unlikely) or move to the top with other apt stuff
RUN apt-get -y install libgoogle-perftools-dev && apt-get clean
ENV LD_PRELOAD=libtcmalloc.so

ARG SHA=89f9faa63388756314e8a1d96cf86bf5e0663045
RUN --mount=type=cache,target=/root/.cache/pip \
    cd stable-diffusion-webui && \
    git fetch && \
    git reset --hard ${SHA} && \
    pip install -r requirements_versions.txt

RUN --mount=type=cache,target=/root/.cache/pip  pip install -U opencv-python-headless

############################# 
#     extension models     #
#############################

FROM base as extensions

COPY ./init /init
RUN mkdir -p /sd-prompt-translator && python /init/sd-prompt-translator.py /sd-prompt-translator

############################# 
#        Lora & VAE         #
#############################
FROM alpine:3.17 as models

RUN apk add --no-cache aria2

RUN aria2c -x 8 --dir "/" --out "codeformer-v0.1.0.pth" "https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth"  
RUN aria2c -x 8 --dir "/" --out "detection_Resnet50_Final.pth" "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" 
RUN aria2c -x 8 --dir "/" --out "parsing_parsenet.pth" "https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/parsing_parsenet.pth" 

RUN aria2c -x 8 --dir "/" --out "cIF8Anime2.43ol.ckpt" "https://civitai.com/api/download/models/34559?type=VAE&format=Other"
RUN aria2c -x 8 --dir "/" --out "vae-ft-mse-840000-ema-pruned.safetensors" "https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors"

RUN aria2c -x 8 --dir "/" --out "moxin.safetensors" "https://civitai.com/api/download/models/14856?type=Model&format=SafeTensor&size=full&fp=fp16"
RUN aria2c -x 8 --dir "/" --out "milkingMachine_v11.safetensors" "https://civitai.com/api/download/models/20705?type=Model&format=SafeTensor&size=full&fp=fp16" 
RUN aria2c -x 8 --dir "/" --out "blingdbox_v1_mix.safetensors" "https://civitai.com/api/download/models/32988?type=Model&format=SafeTensor&size=full&fp=fp16" 
RUN aria2c -x 8 --dir "/" --out "GachaSpliash4.safetensors" "https://civitai.com/api/download/models/38884?type=Model&format=SafeTensor" 
RUN aria2c -x 8 --dir "/" --out "Colorwater_v4.safetensors" "https://civitai.com/api/download/models/21173?type=Model&format=SafeTensor&size=full&fp=fp16" 


############################# 
#           dist            #
#############################

FROM base as dist

RUN mkdir -p /stable-diffusion-webui/models/Stable-diffusion

# copy sd-resource
COPY ./sd-resource ${ROOT}/sd-resource
RUN cp -r ${ROOT}/sd-resource/* ${ROOT} && rm -rf ${ROOT}/sd-resource

# copy extensions pre-download models
COPY --from=extensions /sd-prompt-translator  ${ROOT}/extensions/sd-prompt-translator/scripts/models

# copy Lora and VAE
COPY --from=models /codeformer-v0.1.0.pth /stable-diffusion-webui/models/Codeformer/codeformer-v0.1.0.pth
COPY --from=models /detection_Resnet50_Final.pth /stable-diffusion-webui/repositories/CodeFormer/weights/facelib/detection_Resnet50_Final.pth
COPY --from=models /parsing_parsenet.pth /stable-diffusion-webui/repositories/CodeFormer/weights/facelib/parsing_parsenet.pth

COPY --from=models /cIF8Anime2.43ol.ckpt /stable-diffusion-webui/models/VAE/cIF8Anime2.43ol.ckpt
COPY --from=models /vae-ft-mse-840000-ema-pruned.safetensors /stable-diffusion-webui/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors

COPY --from=models /moxin.safetensors /stable-diffusion-webui/models/Lora/moxin.safetensors
COPY --from=models /milkingMachine_v11.safetensors /stable-diffusion-webui/models/Lora/milkingMachine_v11.safetensors
COPY --from=models /blingdbox_v1_mix.safetensors /stable-diffusion-webui/models/Lora/blingdbox_v1_mix.safetensors
COPY --from=models /GachaSpliash4.safetensors /stable-diffusion-webui/models/Lora/GachaSpliash4.safetensors
COPY --from=models /Colorwater_v4.safetensors /stable-diffusion-webui/models/Lora/Colorwater_v4.safetensors 

COPY . /docker
RUN rm -rf /docker/sd-resource

RUN \
    python3 /docker/info.py ${ROOT}/modules/ui.py && \
    mv ${ROOT}/style.css ${ROOT}/user.css && \
    # one of the ugliest hacks I ever wrote \
    sed -i 's/in_app_dir = .*/in_app_dir = True/g' /usr/local/lib/python3.10/site-packages/gradio/routes.py && \
    git config --global --add safe.directory '*'

WORKDIR ${ROOT}
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_VISIBLE_DEVICES=all
ENV CLI_ARGS="--xformers --disable-safe-unpickle --no-half-vae --enable-insecure-extension-access --skip-version-check --no-download-sd-model"
EXPOSE 7860
ENTRYPOINT ["/docker/entrypoint.sh"]
CMD python -u webui.py --listen --port 7860 ${CLI_ARGS}