edition: 1.0.0
name: fc-stable-diffusion
access: default
vars:
  region: "{{ region }}" 
  functionName: "{{ functionName }}" 
  imageUrl: "{{ imageUrl }}" 

  service:
    name: "fc-stable-diffusion"
    description: 'stable-diffusion部署到函数计算'
    internetAccess: true
services:
  stable-diffusion:
    component: fc
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: ${vars.functionName}
        handler: index.handler
        timeout: 600
        diskSize: 512
        caPort: 7860
        instanceType: fc.gpu.tesla.1
        runtime: custom-container
        cpu: 8
        customContainerConfig:
          args: ''
          accelerationType: Default
          image: ${vars.imageUrl}
          accelerationInfo:
            status: Preparing
          command: ''
          webServerMode: true
        instanceConcurrency: 100
        memorySize: 32768
        environmentVariables: {}
        gpuMemorySize: 16384
        asyncConfiguration: {}
      triggers:
        - name: defaultTrigger
          description: ''
          type: http
          qualifier: LATEST
          config:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            authType: anonymous
            disableURLInternet: false
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*